// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package data.Weekly_sales

object WeeklySalesProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      data.Weekly_sales.WeeklySales
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChJXZWVrbHlfc2FsZXMucHJvdG8SBGRhdGEi0QEKC1dlZWtseVNhbGVzEiAKBXN0b3JlGAEgASgJQgriPwcSBXN0b3JlUgVzd
  G9yZRIdCgRkZXB0GAIgASgJQgniPwYSBGRlcHRSBGRlcHQSHQoEZGF0ZRgDIAEoCUIJ4j8GEgRkYXRlUgRkYXRlEjMKDHdlZWtse
  V9zYWxlcxgEIAEoAkIQ4j8NEgt3ZWVrbHlTYWxlc1ILd2Vla2x5U2FsZXMSLQoKaXNfaG9saWRheRgFIAEoCEIO4j8LEglpc0hvb
  GlkYXlSCWlzSG9saWRheWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}